# Generated by Django 5.1.7 on 2025-05-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(default='En Curso', max_length=100),
        ),
    ]
