# Generated by Django 5.1.7 on 2025-05-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='capacidad',
            field=models.CharField(default='25', max_length=100),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='estado',
            field=models.CharField(default='Disponible', max_length=100),
        ),
    ]
