# Generated by Django 5.1.7 on 2025-03-28 00:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credenciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150, unique=True)),
                ('contrasenia', models.CharField(max_length=255)),
                ('vencido', models.BooleanField(default=False)),
                ('habilitado', models.BooleanField(default=True)),
                ('bloqueado', models.BooleanField(default=False)),
                ('rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('edad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('credenciales', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='cliente.credenciales')),
            ],
        ),
    ]
